homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: metric
  time_zone: !secret timezone
  packages: !include_dir_named packages
  customize:
    sensor.birthday:
      icon: mdi:cake-variant

system_log:

logger:
  default: warn

frontend:
config:

http:
  api_password: !secret http_api_password
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

updater:
discovery:
conversation:
history:
logbook:
map:
sun:

ios:
  push:
    categories:
      - name: Trash Recycle
        identifier: 'trash_recycle'
        actions:
          - identifier: 'TRASH_LEFT'
            title: 'Done'
            activationMode: 'background'
            authenticationRequired: yes
            destructive: yes
            behavior: 'default'
          - identifier: 'TRASH_REMIND_LATER'
            title: 'Remind Later'
            activationMode: 'background'
            authenticationRequired: yes
            destructive: yes
            behavior: 'default'

sensor: !include_dir_merge_list sensors

camera: !include cameras.yaml

input_select: !include input_select.yaml

# Text to speech
tts:
  platform: google

climate:
  platform: homematic

homematic:
  local_ip: !secret hm_ip
  interfaces:
    rf: 
      host: !secret homematic_ip
      port: 2001 
      resolvenames: xml
    ip:
      host: !secret homematic_ip
      port: 2010
    groups:
      host: !secret homematic_ip
      port: 9292
      resolvenames: xml
      path: /groups
  hosts:
    ccu2:
      host: !secret homematic_ip
      username: !secret homematic_user
      password: !secret homematic_password

vacuum:
  platform: roomba
  host: !secret irobot_ip
  username: !secret irobot_username
  password: !secret irobot_password
  name: Roomcajsz

light: 
  platform: hue
  host: !secret hue_ip

device_tracker:
  - platform: nmap_tracker
    hosts: 192.168.0.1-255
    consider_home: 300
    interval_seconds: 20
    track_new_devices: false
  - platform: upc_connect
    host: !secret upc_connect_ip

media_player: !include media_players.yaml
zone: !include zones.yaml
group: !include groups.yaml
automation: !include automations.yaml
