- platform: yr
- platform: uptime

- platform: speedtest
  minute: 30
  hour:
    - 0
    - 12
  monitored_conditions:
    - ping
    - download
    - upload

- platform: rest
  name: Birthday  
  resource: !secret qnap_web_birthday_url 
  scan_intercal: 14400
  value_template: >
    {% set today = now().month  ~ '/' ~ now().day  %}
    {% set event =  value_json.Birthdays.static[ today ] %}
    {{ event }}
    
- platform: rest
  name: fact_of_the_day
  resource: http://api.icndb.com/jokes/random?firstName=Chuck&lastName=Norris&limitTo=[nerdy]
  value_template: '{{ value_json.value.joke }}'
  scan_interval: 86400

- platform: darksky
  api_key: !secret darksky_api_key                          
  name: Weather
  monitored_conditions:
    - summary
    - icon
    - nearest_storm_distance
    - nearest_storm_bearing
    - precip_intensity
    - precip_probability
    - temperature
    - apparent_temperature
    - wind_speed
    - wind_bearing
    - cloud_cover
    - humidity
    - pressure
    - visibility
    - ozone
    - minutely_summary
    - hourly_summary
    - daily_summary
    - temperature_max
    - temperature_min

- platform: qnap
  host: !secret qnap_ip                          
  username: !secret qnap_user                        
  password: !secret qnap_password         
  nics: eth0
  monitored_conditions:
    - status
    - memory_percent_used
    - cpu_usage
    - cpu_temp
    - network_tx
    - network_rx
    - volume_size_free
    - volume_size_used
    - volume_percentage_used

- platform: google_travel_time
  api_key: !secret google_travel_time_api_key
  name: Zsolti to work
  origin: zone.Home
  destination: zone.Work
  options:
    mode: transit
    
- platform: google_travel_time
  api_key: !secret google_travel_time_api_key
  name: Donat to school
  origin: zone.Home
  destination: zone.DonatSchool
  options:
    mode: transit

- platform: command_line
  name: badlogin
  command: grep -c 'Login attempt' /home/hass/.homeassistant/home-assistant.log

- platform: command_line
  name: CPU Temperature
  command: "cat /sys/class/thermal/thermal_zone0/temp"
  unit_of_measurement: "C"
  value_template: '{{ value | multiply(0.001) }}'
